/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'markcafaro' at '7/1/16 11:47 AM' with Gradle 2.14
 *
 * @author markcafaro, @date 7/1/16 11:47 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
